#!/usr/bin/env python3
"""Derived run-state projection.

Markdown remains canonical. This tool reads a run directory and writes
`state/projection.json` plus `state/events.jsonl` as machine-friendly caches.
Never edit Markdown from this projection.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from evidence_parse import parse_evidence  # noqa: E402

SCHEMA = 1
HWS = r"[^\S\n]"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _field(block: str, name: str) -> str:
    pat = rf"(?im)^[ \t]*[-*]?[ \t]*{re.escape(name)}[ \t]*[:：][ \t]*(.*)$"
    m = re.search(pat, block)
    return m.group(1).strip() if m else ""


def parse_fronts(run_dir: Path) -> list[dict]:
    text = _read(run_dir / "frontier.md")
    fronts: list[dict] = []
    for m in re.finditer(rf"(?ms)^###{HWS}+((?:F|H)-\d+)(.*?)(?=^###{HWS}+(?:F|H)-\d+|\Z)", text):
        block = m.group(0)
        head = block.splitlines()[0].strip()
        status = (_field(block, "Status") or "unknown").lower()
        barrier = (_field(block, "Barrier class") or "unknown").lower()
        depth = (_field(block, "Current depth") or _field(block, "Depth") or "unknown").lower()
        fronts.append({
            "id": m.group(1),
            "title": re.sub(r"^###\s*", "", head),
            "status": status,
            "barrier": barrier,
            "depth": depth,
            "same_barrier_failures": len(re.findall(r"same[- ]barrier|同一屏障", block, re.I)),
            "text": block,
        })
    return fronts


def load_coverage(run_dir: Path) -> dict:
    for p in [run_dir / "coverage.json", *sorted(run_dir.glob("**/coverage.json"))]:
        if p.exists():
            try:
                data = json.loads(p.read_text(encoding="utf-8", errors="replace"))
                if isinstance(data, dict):
                    return data
            except Exception:
                continue
    return {"assets": []}


def parse_decisions(run_dir: Path) -> list[dict]:
    text = _read(run_dir / "decisions.md")
    out = []
    for m in re.finditer(r"(?ms)^##\s+(D-\d+).*?(?=^##\s+D-\d+|\Z)", text):
        block = m.group(0)
        out.append({
            "id": m.group(1),
            "time": _field(block, "Time"),
            "chosen_front": _field(block, "Chosen front"),
            "result": _field(block, "Result"),
        })
    return out


def derive(run_dir: Path) -> dict:
    evidence = parse_evidence(run_dir)
    return {
        "schema": SCHEMA,
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "canonical": "markdown",
        "note": "Derived cache only; do not edit this file as source of truth.",
        "fronts": parse_fronts(run_dir),
        "evidence": evidence,
        "coverage": load_coverage(run_dir),
        "decisions": parse_decisions(run_dir),
    }


def _events(proj: dict) -> list[dict]:
    events: list[dict] = []
    seq = 0

    def add(kind: str, **data) -> None:
        nonlocal seq
        seq += 1
        events.append({"seq": seq, "type": kind, **data})

    for f in proj.get("fronts", []):
        add("front", id=f.get("id"), status=f.get("status"), barrier=f.get("barrier"), depth=f.get("depth"))
        if f.get("status"):
            add("status", object=f.get("id"), status=f.get("status"))
    for d in proj.get("decisions", []):
        add("action", id=d.get("id"), front=d.get("chosen_front"), result=d.get("result"))
    for e in proj.get("evidence", []):
        add("evidence", id=e.get("id"), maturity=e.get("maturity"), certainty=e.get("certainties"),
            confirmed=e.get("confirmed"), trust=e.get("trust"))
    return events


def write_projection(run_dir: Path) -> dict:
    proj = derive(run_dir)
    state = run_dir / "state"
    state.mkdir(parents=True, exist_ok=True)
    (state / "projection.json").write_text(json.dumps(proj, ensure_ascii=False, indent=2) + "\n",
                                           encoding="utf-8")
    with (state / "events.jsonl").open("w", encoding="utf-8") as f:
        for ev in _events(proj):
            f.write(json.dumps(ev, ensure_ascii=False) + "\n")
    return proj


def load_or_create(run_dir: Path) -> dict:
    p = run_dir / "state" / "projection.json"
    if p.exists():
        try:
            data = json.loads(p.read_text(encoding="utf-8", errors="replace"))
            if isinstance(data, dict) and data.get("schema") == SCHEMA:
                return data
        except Exception:
            pass
    return write_projection(run_dir)


def _selftest() -> int:
    import tempfile
    d = Path(tempfile.mkdtemp())
    (d / "frontier.md").write_text(
        "# Frontier\n\n### F-001 Login\n- Status: open\n- Barrier class: none\n- Current depth: shallow\n",
        encoding="utf-8")
    (d / "decisions.md").write_text(
        "# Decisions\n\n## D-001\n- Time: now\n- Chosen front: F-001\n- Result: probed\n",
        encoding="utf-8")
    (d / "evidence.md").write_text(
        "# Evidence Ledger\n\n## E-001\n- Maturity: candidate\n- Certainty: 0.5\n",
        encoding="utf-8")
    proj = write_projection(d)
    events = (d / "state" / "events.jsonl").read_text(encoding="utf-8").splitlines()
    checks = [
        ("projection marks markdown canonical", proj.get("canonical") == "markdown"),
        ("front parsed", proj["fronts"][0]["id"] == "F-001" and proj["fronts"][0]["status"] == "open"),
        ("evidence projected", proj["evidence"][0]["id"] == "E-001"),
        ("events written", any('"type": "evidence"' in line for line in events)),
        ("load_or_create reads existing projection", load_or_create(d)["schema"] == SCHEMA),
    ]
    bad = [n for n, ok in checks if not ok]
    for n, ok in checks:
        print(("ok   " if ok else "FAIL ") + n)
    print("state_project selftest " + ("passed" if not bad else f"FAILED ({len(bad)})"))
    return 0 if not bad else 1


def main() -> int:
    ap = argparse.ArgumentParser(description="Project a run's Markdown state into JSON/JSONL caches.")
    ap.add_argument("run_dir", nargs="?")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return _selftest()
    if not args.run_dir:
        ap.error("run_dir is required")
    proj = write_projection(Path(args.run_dir))
    print(json.dumps({"state": str(Path(args.run_dir) / "state"), "fronts": len(proj["fronts"]),
                      "evidence": len(proj["evidence"])}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
